### ISSUE TITLE
Big is not a function

### ISSUE THREAD

**Issue by chrisvoo** [wbond/vat-moss.js#4]
Hi,
I'm just testing this module with Jest, but as soon as I import it (using either `require` or `import`), I get `TypeError: Big is not a function`.
I've also tried to install `big.js` adding `"big.js": "^3.1.3",` to my `package.json` but I get the same result.
What could it be the problem?

**Comment by chrisvoo** [comment]
Ok, I've found that the problem is derived from this check inside `vat-moss.js`:

```javascript
  if (typeof window === 'undefined') {
      var Big = require('big.js');
  } else {
      var Big = window.Big;
  }
```
In my Jest test, `window` results to be defined, so in the end I get this error. As a workaround, if I do `window.Big = require('big.js');` I don't get that error.

**Comment by herkyl** [comment]
Glad you got it working 👍
