### ISSUE TITLE
Removing UK because of the VAT area because of the brexit

### ISSUE THREAD

**Issue by DigitalLeaves** [wbond/vat-moss.js#5]
UK should be removed :)

**Comment by herkyl** [comment]
At this time the [UK still uses VAT](https://www.gov.uk/vat-rates). If things are to change after December 2020 once the Brexit transition ends we should definitely go over it.

**Comment by DigitalLeaves** [comment]
Dear Serge,

Let me consult that information, because we made an inquiry to the tax office and their answer was that, starting 1st of Feb 2020, the UK was to be considered a third country, and outside the VAT area.
Best regards

**Comment by herkyl** [comment]
@DigitalLeaves I've been getting conflicting info on this. Will get back to you.

**Comment by herkyl** [comment]
Confirmed it with my accountant and the internet. Still seems like nothing is to change before December 2020.

**Comment by DigitalLeaves** [comment]
Thank you! my company actually met a representative from the tax office and indeed, while there is a lot of confusion, it seems VAT rules still apply for UK companies and individuals, even for digital services, until Dec. 2020. Sorry for the bothering and thanks for having a look at this!!!
